spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/usercred
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 6963

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka